### ISSUE TITLE
Binder Link on README.md is not working!

### ISSUE THREAD

**Issue by SerkanSipahi** [madou/typescript-transformer-handbook#17]
see binder link: https://github.com/madou/typescript-transformer-handbook/#binder
(https://basarat.gitbook.io/typescript/docs/compiler/binder.htmlhttps:/basarat.gitbooks.io/typescript/docs/compiler/binder)

**Comment by rifler** [comment]
i fixed it here - https://github.com/madou/typescript-transformer-handbook/pull/18
